version: "3"

services:
  serposcope:
    build: .
    image: winterrific/serposcope
    restart: unless-stopped
#    ports:
#      - 7134:7134
    volumes:
      - ./data:/var/lib/serposcope
    networks:
      - traefik
    labels:
      - traefik.http.routers.web.rule=Host(`seo.winterrific.cloud`)
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=le
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.docker.network=traefik

networks:
  traefik:
    external: true
